{% set version = "0.6.1" %}

package:
  name: symengine-wheels
  version: {{ version }}

source:
  - url: https://github.com/symengine/symengine.py/archive/v{{ version }}.tar.gz
    sha256: 8da65b0a693d19b0030461c655a223d20a9164d7d04dd1317c41d6988dc1ec96
    patches:
      - gh341.patch
    folder: python

  - url: https://github.com/symengine/symengine/releases/download/v0.6.0/symengine-0.6.0.tar.gz
    sha256: 4d2caa86c03eaaa8ed004084d02f87b5c51b6229f8ba70d161227e22d6302f0a
    folder: cxx

build:
  number: 4

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make   # [unix]
    - ninja  # [win]
    - unzip           # [unix]
    - patchelf        # [linux]
    - python          # [build_platform != target_platform]
    - cython          # [build_platform != target_platform]
    - cross-python_{{ target_platform }}      # [build_platform != target_platform]
  host:
    - gmp           # [unix]
    - mpir          # [win]
    - mpfr
    - mpc
    - libflint
    - llvmdev  9.*     # [unix]
    - llvmdev  8.*     # [win]
    - python
    - cython
    - setuptools
    - auditwheel      # [linux]
    - delocate        # [osx]
  run:
    - python

about:
  home: https://github.com/symengine/symengine.py
  license: MIT
  license_file: LICENSE
  summary: Python wrappers for SymEngine, a fast symbolic manipulation library, written in C++

extra:
  recipe-maintainers:
    - isuruf
    - certik
