{% set version = "0.6.1" %}

package:
  name: symengine-wheels
  version: {{ version }}

source:
  - url: https://github.com/symengine/symengine.py/archive/v{{ version }}.tar.gz
    sha256: 8da65b0a693d19b0030461c655a223d20a9164d7d04dd1317c41d6988dc1ec96
    patches:
      - gh341.patch
      - debug.diff
    folder: python

  - url: https://github.com/symengine/symengine/releases/download/v0.6.0/symengine-0.6.0.tar.gz
    sha256: 4d2caa86c03eaaa8ed004084d02f87b5c51b6229f8ba70d161227e22d6302f0a
    folder: cxx
    patches:
      - gh1654.patch
      - gh1678.patch
      - gh1691.patch

build:
  number: 4
  skip: true   # [py != 38]
  ignore_run_exports_from:
    - gmp
    - mpfr
    - mpc
    - libflint
    - llvmdev
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make   # [unix]
    - ninja  # [win]
    - unzip           # [unix]
    - patchelf        # [linux]
    - python          # [build_platform != target_platform]
    - cross-python_{{ target_platform }}      # [build_platform != target_platform]
    - auditwheel      # [linux]
    - delocate        # [osx or win]
    - cython
  host:
    - gmp           # [unix]
    - mpir          # [win]
    - mpfr
    - mpc
    - libflint 2.* *nontl*
    - llvmdev          # [unix]
    - llvmdev  8.*     # [win]
    - python
    - setuptools
    - cython
    - pip
  run:
    - python

test:
  requires:
    - pytest
    - sympy
    - numpy

about:
  home: https://github.com/symengine/symengine.py
  license: MIT
  license_file: python/LICENSE
  summary: Python wrappers for SymEngine, a fast symbolic manipulation library, written in C++

extra:
  recipe-maintainers:
    - isuruf
    - certik
