{% set version = "0.7.0.post1" %}

package:
  name: symengine-wheels
  version: {{ version }}

source:
  - url: https://github.com/symengine/symengine.py/archive/v{{ version }}.tar.gz
    sha256: 00ca96c3ae8ebff9a4a3208af8e0f09ceb5d786ad0e02da5c42185761e6a4063
    folder: python

  - url: https://github.com/symengine/symengine/releases/download/v0.7.0/symengine-0.7.0.tar.gz
    sha256: 8b865bb72b71539d9cd2488a0468c6c3ea90cc606062a7880c3ff5af6abd74b1
    folder: cxx

build:
  number: 0
  skip: true  # [(ppc64le or aarch64) and python_impl == "pypy"]
  ignore_run_exports_from:
    - gmp
    - mpfr
    - mpc
    - libflint
    - llvmdev
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make   # [unix]
    - ninja  # [win]
    - unzip           # [unix]
    - patchelf        # [linux]
    - python          # [build_platform != target_platform]
    - cross-python_{{ target_platform }}      # [build_platform != target_platform]
    - auditwheel      # [linux]
    - delocate        # [win]
    - pip             # [osx]
    - cython
  host:
    - gmp           # [unix]
    - mpir          # [win]
    - mpfr
    - mpc
    - libflint 2.* *nontl*
    - llvmdev
    - python
    - setuptools
    - cython
    - pip
  run:
    - python

test:
  requires:
    - pytest
    - sympy
    - numpy

about:
  home: https://github.com/symengine/symengine.py
  license: MIT
  license_file: python/LICENSE
  summary: Python wrappers for SymEngine, a fast symbolic manipulation library, written in C++

extra:
  recipe-maintainers:
    - isuruf
    - certik
