provider:
  linux_64: github_actions
  osx_64: github_actions
  win_64: github_actions
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
  osx_arm64: osx_64
test_on_native_only: True
skip_render:
  - README.md
